### ISSUE TITLE
Request issue

### ISSUE THREAD

**Issue by foxandr** [noeldelgado/metallum#3]
Now, script fails with error - "ValueError: No JSON object could be decoded". 
[metallum.txt](https://github.com/noeldelgado/metallum/files/7534067/metallum.txt)

I'm not a python developer, but an adding of headers to a request solves this issue.
`headers = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0'}`
`....`
`req = Request(url = url, headers = headers)`
`return json.load(urlopen(req))['aaData']`

**Comment by noeldelgado** [comment]
Thanks for the info Aleksandr!
I just pushed some changes for this
